name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: ENV_FILE
          script: |
            # 1. EC2 서버의 app 폴더 생성 및 이동
            mkdir -p ~/app
            cd ~/app

            # 2. .git 존재 여부에 따른 코드 동기화 (git clone / git pull)
            if [ ! -d ".git" ]; then
              git clone -b develop https://github.com/NtropyKB7/ai.git .
            else
              git checkout develop
              git pull origin develop
            fi

            # 3. 최상위 루트 경로에 .env 파일 동적 생성
            echo "$ENV_FILE" > .env

            # 4. 컨테이너 재설치 및 무중단 재배포 (down 에러 방지 구문 포함)
            docker-compose down || true
            docker-compose up --build -d